POST /1djlwbe1 HTTP/1.1
Host: example.com
Accept-Encoding: gzip
X-Request-Id: 56a101b9-e75d-454c-8370-ad1e569158df
User-Agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
Content-Type: application/json
Connect-Time: 4
Via: 1.1 vegur
Content-Length: 559
Total-Route-Time: 8138
Connection: close

{"data": {"domain": {"id": 415995, "name": "example.zone", "state": "hosted", "account_id": 111, "auto_renew": false, "created_at": "2018-11-04T20:51:45Z", "expires_on": null, "updated_at": "2018-11-07T17:13:29Z", "unicode_name": "example.zone", "private_whois": false, "registrant_id": null}}, "name": "domain.resolution_disable", "actor": {"id": "1120", "entity": "user", "pretty": "xxxxx@xxxxxxx.xxx"}, "account": {"id": 111, "display": "Personal", "identifier": "xxxxxx"}, "api_version": "v2", "request_identifier": "a17f32d8-9472-4235-8262-5a7f69214b2c"}
