POST /170zjup1 HTTP/1.1
Host: example.com
Content-Type: application/json
Accept-Encoding: gzip
Content-Length: 750
Via: 1.1 vegur
Total-Route-Time: 0
X-Request-Id: 931853aa-64e5-47ad-bf87-4cff0d091668
User-Agent: DNSimple-Webhook-Notifier/8fd98a84516b72d5b863b27f93fcbaef61f06c03
Connect-Time: 1
Connection: close

{"data": {"domain": {"id": 235146, "name": "dnsimple.xyz", "state": "registered", "account_id": 1111, "auto_renew": true, "created_at": "2016-03-17T08:39:06Z", "expires_on": "2021-03-17", "updated_at": "2019-12-20T08:20:19Z", "unicode_name": "dnsimple.xyz", "private_whois": true, "registrant_id": 2511}, "whois_privacy": {"id": 45425, "enabled": true, "domain_id": 235146, "created_at": "2019-05-17T11:50:29Z", "expires_on": "2021-05-17", "updated_at": "2020-04-26T12:08:55Z"}}, "name": "whois_privacy.renew", "actor": {"id": "system", "entity": "dnsimple", "pretty": "support@dnsimple.com"}, "account": {"id": 1111, "display": "xxxxxxxx", "identifier": "xxxxxxxx"}, "api_version": "v2", "request_identifier": "edefcd87-8cf8-41cb-86b4-9e67a62b04e7"}
