POST /1djlwbe1 HTTP/1.1
host: example.com
content-length: 557
accept-encoding: gzip
x-request-id: 42f14e6a-21e4-4942-9556-682298b5a852
user-agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
content-type: application/json
connect-time: 0
via: 1.1 vegur
total-route-time: 1
connection: keep-alive

{"data": {"email_forward": {"id": 11587, "to": "test@example.com", "from": "test@hostedzone.com", "active": false, "domain_id": 322675, "created_at": "2024-11-21T13:21:45Z", "updated_at": "2024-11-21T13:25:51Z", "alias_email": "test@hostedzone.com", "destination_email": "test@example.com"}}, "name": "email_forward.deactivate", "actor": {"id": "1120", "entity": "user", "pretty": "xxxxx@xxxxxxx.xxx"}, "account": {"id": 111, "display": "Personal", "identifier": "xxxxxx"}, "api_version": "v2", "request_identifier": "1c15eea2-cf3e-4613-9f35-3f4bdd79d231"}
