# https://docs.codecov.io/docs/coverage-configuration
coverage:
  precision: 1
  round: down

coverage:
  status:
    patch:
      default: false
    project:
      default: false

# https://docs.codecov.io/docs/pull-request-comments#section-requiring-changes
comment: off
