POST /1djlwbe1 HTTP/1.1
Host: example.com
Content-Type: application/json
User-Agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
Total-Route-Time: 7084
Connect-Time: 1
Via: 1.1 vegur
X-Request-Id: 851509f5-c62e-4c55-bd93-37be8c858bf9
Content-Length: 659
Accept-Encoding: gzip
Connection: close

{"data": {"dnssec": {"enabled": true, "created_at": "2017-07-19T18:52:55Z", "updated_at": "2017-07-19T18:52:55Z"}, "delegation_signer_record": {"id": 5922, "digest": "25074F314A81525B55B7A251F49D9ADBF8B2FD1FC87AF829B27E778F3556794A", "keytag": "34594", "algorithm": "8", "domain_id": 252645, "created_at": "2018-09-27T23:00:00Z", "updated_at": "2018-09-27T23:00:00Z", "digest_type": "2"}}, "name": "dnssec.rotation_start", "actor": {"id": "system", "entity": "dnsimple", "pretty": "support@dnsimple.com"}, "account": {"id": 981, "display": "Personal", "identifier": "weppos"}, "api_version": "v2", "request_identifier": "cf02358a-b2d5-4def-9d6c-ee53ad7fe591"}
