POST /1djlwbe1 HTTP/1.1
Host: example.com
Content-Type: application/json
User-Agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
Total-Route-Time: 6006
Connect-Time: 1
Via: 1.1 vegur
X-Request-Id: 02449375-8d36-45ba-9e73-cdb7615388f0
Content-Length: 658
Accept-Encoding: gzip
Connection: close

{"data": {"dnssec": {"enabled": true, "created_at": "2017-02-06T20:15:05Z", "updated_at": "2017-02-06T20:15:05Z"}, "delegation_signer_record": {"id": 6037, "digest": "BD9D898E92D0F668E6BDBC5E79D52E5C3BAB12823A6EEE8C8B6DC633007DFABC", "keytag": "27472", "algorithm": "8", "domain_id": 41557, "created_at": "2018-10-09T02:00:02Z", "updated_at": "2018-10-09T02:00:02Z", "digest_type": "2"}}, "name": "dnssec.rotation_start", "actor": {"id": "system", "entity": "dnsimple", "pretty": "support@dnsimple.com"}, "account": {"id": 123, "display": "Personal", "identifier": "foobar"}, "api_version": "v2", "request_identifier": "b2ddc716-f621-418c-a6a9-6a2c2d7acd27"}
