POST / HTTP/1.1
host: example.com
accept-encoding: gzip
content-type: application/json
user-agent: DNSimple-Webhook-Notifier/8fd98a84516b72d5b863b27f93fcbaef61f06c03
content-length: 681
connection: keep-alive

{"data": {"domain": {"id": 181984, "name": "example-alpha.com", "state": "registered", "account_id": 1385, "auto_renew": false, "created_at": "2020-06-04T19:15:14Z", "expires_at": "2021-06-05T02:15:00Z", "expires_on": "2021-06-05", "updated_at": "2020-06-04T20:46:16Z", "unicode_name": "example-alpha.com", "private_whois": false, "registrant_id": 2715}}, "name": "domain.auto_renewal_disable", "actor": {"id": "1331", "entity": "user", "pretty": "xxxxxxx-xxxxxxx-xxxxxxx@xxxxx.com"}, "account": {"id": 1385, "display": "xxxxxxx-xxxxxxx-xxxxxxx", "identifier": "xxxxxxx-xxxxxxx-xxxxxxx@xxxxx.com"}, "api_version": "v2", "request_identifier": "abf9d6d1-ea69-45f8-85c8-de32b8c6e845"}
