POST /1djlwbe1 HTTP/1.1
host: example.com
content-type: application/json
content-length: 422
user-agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
connect-time: 0
via: 1.1 vegur
accept-encoding: gzip
x-request-id: cc73ccd6-bb72-4cc9-9f95-6d3010595fdf
total-route-time: 0
connection: keep-alive

{"data": {"zone": {"id": 360320, "name": "example.zone", "reverse": false, "account_id": 123, "created_at": "2018-11-04T20:51:12Z", "updated_at": "2018-11-04T20:51:12Z"}}, "name": "zone.delete", "actor": {"id": "1120", "entity": "user", "pretty": "hello@example.com"}, "account": {"id": 123, "display": "Personal", "identifier": "foobar"}, "api_version": "v2", "request_identifier": "0c783469-92c7-4819-90b6-62ef7785abc5"}
