POST /1djlwbe1 HTTP/1.1
Host: example.com
Accept-Encoding: gzip
X-Request-Id: 25f70239-85cd-49eb-8fc7-29f8a478f906
Content-Length: 577
User-Agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
Content-Type: application/json
Via: 1.1 vegur
Total-Route-Time: 0
Connect-Time: 0
Connection: close

{"data": {"user": {"id": 1008, "email": "xxxxxxxxxx@xxxxx.xxx", "created_at": "2011-03-01T17:15:27Z", "updated_at": "2017-04-18T11:04:50Z"}, "account": {"id": 1111, "email": "xxxxxx@xxxxx.xxx", "created_at": "2012-03-16T16:02:54Z", "updated_at": "2018-11-03T18:11:09Z", "plan_identifier": "dnsimple-professional"}}, "name": "account.remove_user", "actor": {"id": "1120", "entity": "user", "pretty": "hello@example.com"}, "account": {"id": 1111, "display": "xxxxxxxx", "identifier": "xxxxxxxx"}, "api_version": "v2", "request_identifier": "8a38c969-c26e-4fc9-9572-296ab67a9022"}
