POST /1djlwbe1 HTTP/1.1
Host: example.com
Content-Length: 455
Accept-Encoding: gzip
X-Request-Id: 42f14e6a-21e4-4942-9556-682298b5a852
User-Agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
Content-Type: application/json
Connect-Time: 0
Via: 1.1 vegur
Total-Route-Time: 1
Connection: keep-alive

{"data": {"email_forward": {"id": 11587, "to": "test@example.com", "from": "test@hostedzone.com", "domain_id": 322675, "created_at": "2024-11-21T13:21:45Z", "updated_at": "2024-11-21T13:25:51Z", "alias_email": "test@hostedzone.com", "destination_email": "test@example.com"}}, "name": "email_forward.activate", "actor": {"id": "1120", "entity": "user", "pretty": "xxxxx@xxxxxxx.xxx"}, "account": {"id": 111, "display": "Personal", "identifier": "xxxxxx"}, "api_version": "v2", "request_identifier": "1c15eea2-cf3e-4613-9f35-3f4bdd79d231"}
