POST /1djlwbe1 HTTP/1.1
host: example.com
content-type: application/json
content-length: 553
user-agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
connect-time: 0
via: 1.1 vegur
accept-encoding: gzip
x-request-id: d75c6962-5e68-45a2-afe2-3943dd8637fa
total-route-time: 0
connection: keep-alive

{"data": {"zone_record": {"id": 14762434, "ttl": 3600, "name": "www", "type": "A", "content": "127.0.0.1", "regions": ["global"], "zone_id": "example.zone", "priority": null, "parent_id": null, "created_at": "2018-11-04T20:52:21Z", "updated_at": "2018-11-04T20:52:34Z", "system_record": false}}, "name": "zone_record.update", "actor": {"id": "1120", "entity": "user", "pretty": "hello@example.com"}, "account": {"id": 123, "display": "Personal", "identifier": "foobar"}, "api_version": "v2", "request_identifier": "96cc0f56-577d-41bb-beb5-b1a60ceaf049"}
