POST /1djlwbe1 HTTP/1.1
Host: example.com
Content-Type: application/json
User-Agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
Total-Route-Time: 0
Connect-Time: 0
Via: 1.1 vegur
X-Request-Id: 653490f4-34b7-4049-bf08-0f4fbcc98ee3
Content-Length: 639
Accept-Encoding: gzip
Connection: close

{"data": {"zone_record": {"id": 14573574, "ttl": 3600, "name": "_dmarc", "type": "TXT", "content": "v=DMARC1; p=none; pct=100; rua=mailto:re+nyotd6webz9@dmarc.postmarkapp.com; sp=none; aspf=r;", "regions": ["global"], "zone_id": "foobar.net", "priority": null, "parent_id": null, "created_at": "2018-09-25T13:32:40Z", "updated_at": "2018-10-05T12:58:33Z", "system_record": false}}, "name": "zone_record.update", "actor": {"id": "1120", "entity": "user", "pretty": "alpha@example.com"}, "account": {"id": 123, "display": "Personal", "identifier": "foobar"}, "api_version": "v2", "request_identifier": "4348d315-df93-459e-965e-d6a9a03236be"}
