POST /1djlwbe1 HTTP/1.1
host: example.com
accept-encoding: gzip
x-request-id: 7c7d1a66-efc6-4818-9861-ec0ed1a1ddb4
content-length: 350
user-agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
content-type: application/json
via: 1.1 vegur
total-route-time: 0
connect-time: 0
connection: keep-alive

{"data": {"webhook": {"id": 274, "url": "https://xxxxxx-xxxxxxx-00000.herokuapp.com/xxxxxxxx"}}, "name": "webhook.create", "actor": {"id": "1120", "entity": "user", "pretty": "hello@example.com"}, "account": {"id": 123, "display": "Personal", "identifier": "foobar"}, "api_version": "v2", "request_identifier": "f8330285-724f-4395-84ee-063e390d8162"}
