POST /1djlwbe1 HTTP/1.1
host: example.com
accept-encoding: gzip
x-request-id: 4e4b2552-9c80-4437-aea8-b09e8ceb0321
user-agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
content-type: application/json
content-length: 350
via: 1.1 vegur
total-route-time: 0
connect-time: 0
connection: keep-alive

{"data": {"webhook": {"id": 215, "url": "https://xxxxxx-xxxxxxx-00000.herokuapp.com/xxxxxxxx"}}, "name": "webhook.delete", "actor": {"id": "1120", "entity": "user", "pretty": "hello@example.com"}, "account": {"id": 123, "display": "Personal", "identifier": "foobar"}, "api_version": "v2", "request_identifier": "4d6f9084-850d-444d-a998-455a59f830d5"}
