POST /1djlwbe1 HTTP/1.1
Host: example.com
Content-Type: application/json
Content-Length: 547
User-Agent: DNSimple-Webhook-Notifier/f152781ec87b328bf9edcaa760f0e5342bdd15cf
Connect-Time: 0
Via: 1.1 vegur
Accept-Encoding: gzip
X-Request-Id: 03aad23f-59d6-4634-9247-56f02d552df0
Total-Route-Time: 0
Connection: close

{"data": {"domain": {"id": 415993, "name": "example.zone", "state": "hosted", "account_id": 123, "auto_renew": false, "created_at": "2018-11-04T20:51:12Z", "expires_on": null, "updated_at": "2018-11-04T20:51:12Z", "unicode_name": "example.zone", "private_whois": false, "registrant_id": null}}, "name": "domain.delete", "actor": {"id": "1120", "entity": "user", "pretty": "hello@example.com"}, "account": {"id": 123, "display": "Personal", "identifier": "foobar"}, "api_version": "v2", "request_identifier": "24ab825e-40c1-4298-8f49-211332522d9b"}
