POST /170zjup1 HTTP/1.1
Host: example.com
Accept-Encoding: gzip
X-Request-Id: 238da298-7345-474a-b4a6-81e980bc1d20
Content-Type: application/json
User-Agent: DNSimple-Webhook-Notifier/8fd98a84516b72d5b863b27f93fcbaef61f06c03
Connect-Time: 2
Total-Route-Time: 0
Content-Length: 749
Via: 1.1 vegur
Connection: close

{"data": {"account": {"id": 1111, "email": "xxxxx@xxxxxx.xxx", "created_at": "2012-03-16T16:02:54Z", "updated_at": "2020-05-10T18:11:03Z", "plan_identifier": "professional-v1-monthly"}, "account_invitation": {"id": 3523, "email": "xxxxxx@xxxxxx.xxx", "token": "eb5763dc-0f24-420b-b7f6-c7355c8b8309", "account_id": 1111, "created_at": "2020-05-12T18:42:44Z", "updated_at": "2020-05-12T18:42:44Z", "invitation_sent_at": "2020-05-12T18:42:44Z", "invitation_accepted_at": null}}, "name": "account.user_invite", "actor": {"id": "88720", "entity": "user", "pretty": "xxxxxxxxxxxxxxxxx@xxxxxx.xxx"}, "account": {"id": 1111, "display": "xxxxxxxx", "identifier": "xxxxxxxx"}, "api_version": "v2", "request_identifier": "f8f1ffa3-e49b-4ff0-a46a-41dd67094307"}
